-- =============================================================
-- Seed autogenerado desde src/lib/data (npm run seed:sql).
-- Contenido global: biblioteca de ejercicios y rutina base.
-- =============================================================

-- Biblioteca de ejercicios
insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'handstand-libre', 'Handstand libre', 'handstand', '{"handstand","hombros","core"}', '{"peso-corporal"}', 'intermedio', true, '🤸', null, '{"Colocá las manos aproximadamente al ancho de los hombros.","Separá los dedos y presioná el suelo con las yemas.","Mantené los codos extendidos y empujá activamente el suelo.","Elevá los hombros hacia las orejas.","Contraé abdomen y glúteos, piernas juntas.","Mirá entre las manos sin levantar demasiado la cabeza."}', 'Respiración corta y controlada, sin bloquear el aire.', '{"Arquear demasiado la zona lumbar.","Relajar los hombros.","Doblar los codos.","Separar demasiado las piernas.","Hacer demasiados intentos estando fatigado."}', '{"Activá glúteos y abdomen para cerrar la costilla.","Pensá en 'empujar el suelo lejos' para elevar los hombros."}', 'Handstand cara a la pared o contra la pared.', 'Aumentar tiempo en balance libre y reducir la fuerza de entrada.', '{"Práctica contra una pared libre del gimnasio."}', 'Evitar con lesiones de muñeca, hombro o problemas de presión arterial.'
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'handstand-pared', 'Handstand cara a la pared', 'handstand', '{"handstand","hombros","core"}', '{"peso-corporal"}', 'principiante', true, '🧱', null, '{"Caminá con los pies por la pared hasta acercar las manos.","Acercá progresivamente las manos a la pared.","Mantené abdomen y glúteos activos.","No apoyes todo el peso en la pared.","Mantené los hombros elevados."}', 'Inhalá al entrar, respiración controlada durante el hold.', '{"Descolgar los hombros.","Arquear la lumbar y apoyar la panza en la pared."}', '{"Buscá la línea vertical con costillas cerradas."}', 'Alejar un poco las manos de la pared.', 'Acercar las manos y sostener 40s con buena línea.', '{"Cualquier pared despejada."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'handstand-tecnico', 'Handstand técnico ligero', 'handstand', '{"handstand","hombros","core"}', '{"peso-corporal"}', 'principiante', true, '🎯', null, '{"Intentos suaves, priorizando línea y control.","No busques fatiga: parás cuando la calidad baja.","Trabajá balance y activación escapular."}', null, '{"Convertirlo en trabajo pesado.","Buscar el fallo."}', '{"Calidad sobre cantidad."}', null, null, '{"Pared despejada."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'pike-pushups', 'Pike push-ups', 'empuje', '{"hombros","brazos","handstand"}', '{"peso-corporal"}', 'principiante', true, '🔺', null, '{"Elevá la cadera formando una V invertida.","Llevá la cabeza hacia adelante y abajo.","Formá un triángulo entre cabeza y manos.","Mantené los codos en un ángulo natural.","Empujá el suelo al subir."}', 'Inhalá al bajar, exhalá al empujar.', '{"Bajar solo con los brazos sin llevar la cabeza adelante."}', '{"Elevá más la cadera para cargar los hombros."}', 'Pike push-up con pies en el suelo.', 'Pies elevados → negativas de HSPU → HSPU asistido en pared.', '{"Press de hombros en máquina si hay molestia."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'wall-shoulder-taps', 'Shoulder taps en pared', 'handstand', '{"hombros","core","handstand"}', '{"peso-corporal"}', 'intermedio', true, '👐', null, '{"En handstand cara a la pared, separá ligeramente los pies.","Transferí el peso hacia una mano.","Mantené el core activo y despegá la mano de forma controlada.","Evitá girar demasiado la cadera."}', null, '{"Colapsar la cadera al transferir el peso."}', '{"Movimiento lento, sin rebotes."}', 'Shoulder taps en posición de pike o cambios de peso sin despegar la mano.', 'Aumentar repeticiones y tiempo de apoyo en una mano.', '{"Pared despejada."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'handstand-scapular-shrugs', 'Scapular shrugs en handstand', 'handstand', '{"hombros","handstand"}', '{"peso-corporal"}', 'intermedio', true, '🪜', null, '{"En handstand contra la pared, mantené los codos completamente extendidos.","Elevá y descendé el cuerpo únicamente con las escápulas.","No flexiones los brazos. Usá un rango pequeño y controlado."}', null, '{"Flexionar los codos.","Rango excesivo."}', '{"Aislá el movimiento en las escápulas."}', null, null, '{"Pared despejada."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'smith-shoulder-press', 'Press de hombros en Smith machine', 'hombros', '{"hombros","brazos"}', '{"smith","banco"}', 'principiante', false, '🏋️', null, '{"Ajustá el banco casi vertical.","Colocá la barra aproximadamente a la altura del mentón.","Mantené los antebrazos verticales.","Descendé de forma controlada.","Empujá sin arquear excesivamente la espalda.","Mantené los pies firmes."}', 'Inhalá al bajar, exhalá al empujar.', '{"Bajar la barra detrás de la cabeza.","Separar excesivamente los codos.","Usar demasiado peso.","Rebotar en la parte inferior."}', '{"Reducí el peso hasta controlar el rango completo."}', null, 'Progresión doble en peso dentro del rango de reps.', '{"Press de hombros en máquina o con mancuernas."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'dips', 'Fondos (asistidos o libres)', 'empuje', '{"pecho","brazos","hombros"}', '{"peso-corporal","maquina"}', 'principiante', true, '💪', null, '{"Mantené hombros abajo y atrás.","Inclinate ligeramente hacia adelante para enfatizar pecho.","Descendé hasta que el hombro esté aproximadamente al nivel del codo.","No dejes que los hombros colapsen.","Extendé los brazos sin bloquear violentamente."}', 'Inhalá al bajar, exhalá al subir.', '{"Colapsar los hombros.","Rango incompleto."}', '{"Usá asistencia para mantener técnica."}', 'Fondos asistidos en máquina o negativas controladas.', 'Menos asistencia → libres → lastre.', '{"Máquina de fondos asistidos (assisted dip)."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'incline-db-press', 'Press inclinado con mancuernas', 'empuje', '{"pecho","hombros","brazos"}', '{"mancuerna","banco"}', 'principiante', false, '🛏️', null, '{"Banco inclinado entre 20 y 35 grados.","Escápulas retraídas, pies firmes.","Bajá las mancuernas de manera controlada.","Mantené las muñecas neutras.","No choques las mancuernas arriba."}', 'Inhalá al bajar, exhalá al empujar.', '{"Inclinación excesiva.","Chocar mancuernas arriba."}', '{"Controlá la fase excéntrica."}', null, 'Progresión doble: subir de mancuerna al completar el rango.', '{"Press inclinado en máquina o Smith."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'pec-deck', 'Peck deck (aperturas en máquina)', 'empuje', '{"pecho"}', '{"maquina"}', 'principiante', false, '🦋', null, '{"Ajustá el asiento para que los brazos queden alineados con el pecho.","Mantené el pecho elevado.","Juntá los brazos sin encorvar los hombros.","Regresá lentamente."}', 'Exhalá al juntar, inhalá al abrir.', '{"Encorvar los hombros hacia adelante."}', '{"Mantené el pecho arriba durante todo el rango."}', null, null, '{"Cruce de poleas (cable crossover)."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'machine-chest-press', 'Press de pecho en máquina', 'empuje', '{"pecho","hombros","brazos"}', '{"maquina"}', 'principiante', false, '🎚️', null, '{"Ajustá el asiento para que las manijas queden a la altura del pecho.","Escápulas retraídas, pecho arriba.","Empujá de forma controlada sin bloquear violentamente."}', 'Exhalá al empujar.', '{"Elevar los hombros al empujar."}', '{"Fijá las escápulas contra el respaldo."}', null, null, '{"Press con mancuernas o Smith."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'lateral-raises', 'Elevaciones laterales', 'hombros', '{"hombros"}', '{"mancuerna","polea"}', 'principiante', false, '🕊️', null, '{"Utilizá poco peso.","Elevá los brazos hasta aproximadamente la altura de los hombros.","Mantené los codos levemente flexionados.","Controlá la bajada.","Evitá balancearte."}', 'Exhalá al subir.', '{"Usar demasiado peso y balancearse."}', '{"Bajá el peso y priorizá técnica."}', null, 'Aumentar reps antes que peso.', '{"Elevaciones en polea baja."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'db-shoulder-press', 'Press de hombros con mancuernas', 'hombros', '{"hombros","brazos"}', '{"mancuerna","banco"}', 'principiante', false, '🏋️', null, '{"Sentado con respaldo casi vertical.","Mantené los antebrazos verticales.","Empujá sin arquear excesivamente.","Bajá controlado hasta la altura de las orejas."}', 'Exhalá al empujar.', '{"Arquear la lumbar.","Rango incompleto."}', '{"Activá el core para proteger la lumbar."}', null, null, '{"Press de hombros en máquina o Smith."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'pull-ups', 'Dominadas estrictas', 'traccion', '{"espalda","brazos"}', '{"barra-dominadas","peso-corporal"}', 'intermedio', true, '🧗', null, '{"Iniciá desde brazos extendidos.","Deprimí las escápulas antes de flexionar los codos.","Llevá el pecho hacia la barra.","Evitá el balanceo.","Descendé completamente y con control."}', 'Exhalá al subir.', '{"Balanceo (kipping) involuntario.","Rango incompleto."}', '{"Dejá 1–2 reps en reserva; no entrenar al fallo todas las series."}', 'Dominada asistida, negativas, jalón al pecho o isométricos arriba.', 'Aumentar reps → reducir asistencia → lastre.', '{"Jalón al pecho o dominadas asistidas en máquina."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'lat-pulldown', 'Jalón al pecho', 'traccion', '{"espalda","brazos"}', '{"polea","maquina"}', 'principiante', false, '⬇️', null, '{"Agarre ligeramente más ancho que los hombros.","Inclinate apenas hacia atrás.","Llevá la barra hacia la parte superior del pecho.","No tires detrás de la nuca.","Controlá la subida."}', 'Exhalá al tirar.', '{"Tirar detrás de la nuca.","Usar impulso."}', '{"Iniciá el movimiento deprimiendo las escápulas."}', null, null, '{"Máquina de jalón (lat pulldown)."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'seated-cable-row', 'Remo sentado en polea', 'traccion', '{"espalda","brazos"}', '{"polea"}', 'principiante', false, '🚣', null, '{"Mantené el torso estable.","Llevá los codos hacia atrás.","Juntá las escápulas.","No redondees la espalda.","Evitá impulsarte con el cuerpo."}', 'Exhalá al tirar.', '{"Redondear la espalda.","Impulso con el torso."}', '{"Pausá brevemente en la contracción."}', null, null, '{"Remo en máquina."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'chest-supported-row', 'Remo con pecho apoyado', 'traccion', '{"espalda"}', '{"maquina","mancuerna","banco"}', 'principiante', false, '🪑', null, '{"Mantené el pecho apoyado.","Tirá con los codos.","Evitá elevar los hombros.","Pausá brevemente arriba."}', 'Exhalá al tirar.', '{"Despegar el pecho para usar impulso."}', '{"Mantené el pecho fijo en el apoyo."}', null, null, '{"Remo en máquina con apoyo de pecho."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'machine-row', 'Remo en máquina', 'traccion', '{"espalda","brazos"}', '{"maquina"}', 'principiante', false, '⚙️', null, '{"Ajustá el apoyo de pecho.","Tirá llevando los codos hacia atrás.","Juntá las escápulas y controlá la vuelta."}', 'Exhalá al tirar.', '{"Encogerse de hombros."}', '{"Bajá los hombros y tirá con la espalda."}', null, null, '{"Remo sentado en polea."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'face-pulls', 'Face pulls', 'hombros', '{"hombros","espalda"}', '{"polea","banda"}', 'principiante', false, '🎯', null, '{"Llevá la cuerda hacia la frente.","Separá las manos al final.","Mantené codos altos.","No arquees la espalda."}', 'Exhalá al tirar.', '{"Codos bajos.","Arquear la lumbar."}', '{"Pensá en 'abrir' a la altura de la cara."}', null, null, '{"Cuerda en polea alta o banda."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'triceps-pushdown', 'Extensión de tríceps en polea', 'brazos', '{"brazos"}', '{"polea"}', 'principiante', false, '🔧', null, '{"Mantené los codos pegados al cuerpo.","No muevas los hombros.","Extendé completamente sin balancear el torso."}', 'Exhalá al extender.', '{"Despegar los codos.","Balanceo del torso."}', '{"Fijá los codos a los costados."}', null, null, '{"Extensión con mancuerna sobre la cabeza."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'hammer-curl', 'Curl martillo', 'brazos', '{"brazos"}', '{"mancuerna"}', 'principiante', false, '🔨', null, '{"Mantené los codos quietos.","No balancees el torso.","Controlá la fase de bajada."}', 'Exhalá al subir.', '{"Balancear el torso."}', '{"Reducí el peso y fijá los codos."}', null, null, '{"Curl martillo en polea con cuerda."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'hollow-body-hold', 'Hollow body hold', 'core', '{"core"}', '{"peso-corporal"}', 'principiante', true, '🌙', null, '{"Recostado, presioná la lumbar contra el suelo.","Elevá hombros y piernas manteniendo la costilla cerrada.","Sostené la posición de banana invertida."}', 'Respiración corta y constante.', '{"Despegar la lumbar del suelo."}', '{"Reducí la palanca flexionando rodillas."}', 'Rodillas flexionadas y brazos junto al cuerpo.', 'Piernas extendidas y brazos detrás de la cabeza.', '{"En colchoneta del gimnasio."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'hanging-knee-raises', 'Hanging knee raises', 'core', '{"core"}', '{"barra-dominadas","peso-corporal"}', 'principiante', true, '🪝', null, '{"Colgado de la barra, evitá balancearte.","Llevá la pelvis hacia arriba (no solo levantar las rodillas).","Descendé lentamente."}', 'Exhalá al subir.', '{"Balanceo.","Solo levantar rodillas sin retroversión pélvica."}', '{"Iniciá el movimiento inclinando la pelvis."}', 'Elevaciones en silla romana (captain''s chair).', 'Elevaciones de piernas extendidas.', '{"Silla romana (captain's chair)."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

insert into public.exercises (id,name,category,primary_muscles,equipment,level,is_bodyweight,image_emoji,video_url,instructions,breathing,common_mistakes,corrections,regression,progression,planet_fitness_substitutions,contraindications) values (
  'farmer-carry', 'Farmer carry (transporte)', 'transporte', '{"core","espalda","brazos"}', '{"mancuerna"}', 'principiante', false, '🧳', null, '{"Mantené el pecho elevado.","No te inclines hacia los lados.","Caminá con pasos controlados.","Mantené el abdomen activo y sujetá firme las mancuernas."}', 'Respiración constante durante el recorrido.', '{"Inclinarse hacia un lado."}', '{"Mantené el tronco rígido y vertical."}', null, null, '{"Con mancuernas pesadas o kettlebells si hay."}', null
) on conflict (id) do update set name=excluded.name, category=excluded.category, primary_muscles=excluded.primary_muscles, equipment=excluded.equipment, level=excluded.level, is_bodyweight=excluded.is_bodyweight, image_emoji=excluded.image_emoji, instructions=excluded.instructions, breathing=excluded.breathing, common_mistakes=excluded.common_mistakes, corrections=excluded.corrections, regression=excluded.regression, progression=excluded.progression, planet_fitness_substitutions=excluded.planet_fitness_substitutions, contraindications=excluded.contraindications;

-- Rutina base de 3 días (referencia). El plan por usuario se crea
-- desde la app; este bloque documenta la prescripción canónica.
-- Día A: Día A — Empuje, Handstand y Pecho (weekday 1)
--   [Bloque de handstand]
--     handstand-libre: 10 x 5-15s, rest 40s
--     handstand-pared: 3 x 20-40s, rest 75s
--   [Fuerza e hipertrofia]
--     smith-shoulder-press: 4 x 6-8 reps, rest 120s
--     dips: 4 x 5-10 reps, rest 120s
--     incline-db-press: 3 x 8-12 reps, rest 90s
--     lateral-raises: 3 x 12-20 reps, rest 60s
--     pec-deck: 3 x 10-15 reps, rest 75s
--     triceps-pushdown: 3 x 10-15 reps, rest 60s
--   [Core]
--     hollow-body-hold: 3 x 20-40s, rest 60s
-- Día B: Día B — Espalda, Bíceps y Core (weekday 3)
--   [Handstand técnico ligero]
--     handstand-tecnico: 6 x 5-15s, rest 45s
--   [Fuerza e hipertrofia]
--     pull-ups: 5 x 2-5 reps, rest 150s
--     lat-pulldown: 3 x 8-12 reps, rest 90s
--     seated-cable-row: 4 x 8-12 reps, rest 90s
--     chest-supported-row: 3 x 10-12 reps, rest 90s
--     face-pulls: 3 x 12-20 reps, rest 60s
--     hammer-curl: 3 x 8-12 reps, rest 60s
--   [Core]
--     hanging-knee-raises: 3 x 8-15 reps, rest 60s
-- Día C: Día C — Handstand, Hombros y Tren Superior (weekday 5)
--   [Bloque de handstand]
--     handstand-libre: 10 x 3-12s, rest 45s
--     pike-pushups: 4 x 6-10 reps, rest 90s
--     wall-shoulder-taps: 3 x 4-10 reps, rest 90s
--     handstand-scapular-shrugs: 3 x 8-15 reps, rest 60s
--   [Hombros y tren superior]
--     db-shoulder-press: 3 x 8-12 reps, rest 90s
--     machine-row: 3 x 10-15 reps, rest 90s
--     machine-chest-press: 3 x 8-12 reps, rest 90s
--     lateral-raises: 3 x 15-20 reps, rest 60s
--     farmer-carry: 3 x 30-45s, rest 75s
